#undef SHIFT_DOUBLE_OMITS_COUNT
#define SHIFT_DOUBLE_OMITS_COUNT 1

#undef ASM_COMMENT_START
#define ASM_COMMENT_START "/ "

#undef ASM_APP_ON
#define ASM_APP_ON "/APP\n"

#undef ASM_APP_OFF
#define ASM_APP_OFF "/NO_APP\n"

#undef TEXT_SECTION_ASM_OP
#define TEXT_SECTION_ASM_OP "\t.text"

#undef DATA_SECTION_ASM_OP
#define DATA_SECTION_ASM_OP "\t.data"

#undef BSS_SECTION_ASM_OP
#define BSS_SECTION_ASM_OP "\t.bss"

#undef GLOBAL_ASM_OP
#define GLOBAL_ASM_OP "\t.globl\t"

#undef TARGET_SUBTARGET_DEFAULT
#define TARGET_SUBTARGET_DEFAULT \
	(MASK_80387 | MASK_IEEE_FP | MASK_FLOAT_RETURNS)

#undef TARGET_SUBTARGET64_DEFAULT
#define TARGET_SUBTARGET64_DEFAULT \
        MASK_128BIT_LONG_DOUBLE
